[package]
authors = ["Ivan Enderlin <ivane@element.io>"]
description = "Matrix encryption library, for NodeJS"
edition = "2021"
homepage = "https://github.com/matrix-org/matrix-rust-sdk-nodejs"
keywords = ["matrix", "chat", "messaging", "ruma", "nio"]
license = "Apache-2.0"
name = "matrix-sdk-crypto-nodejs"
readme = "README.md"
repository = "https://github.com/matrix-org/matrix-rust-sdk-nodejs"
rust-version = "1.70"
version = "0.6.0"

[package.metadata.docs.rs]
rustdoc-args = ["--cfg", "docsrs"]

[lib]
crate-type = ["cdylib"]

[features]
default = ["bundled-sqlite"]
bundled-sqlite = ["matrix-sdk-sqlite/bundled"]
qrcode = ["matrix-sdk-crypto/qrcode"]
tracing = ["dep:tracing-subscriber"]

[dependencies]
matrix-sdk-common = { git = "https://github.com/matrix-org/matrix-rust-sdk", rev = "fc3883d08e3ce9d04be39b1fc2867c21b973dbd7", features = ["js"] }
matrix-sdk-sqlite = { git = "https://github.com/matrix-org/matrix-rust-sdk", rev = "fc3883d08e3ce9d04be39b1fc2867c21b973dbd7", features = ["crypto-store"] }
napi = { version = "2.9.1", default-features = false, features = ["napi6", "tokio_rt"] }
napi-derive = "2.9.1"
serde_json = "1.0.91"
http = "0.2.6"
tracing-subscriber = { version = "0.3", default-features = false, features = ["tracing-log", "time", "smallvec", "fmt", "env-filter"], optional = true }
zeroize = "1.3.0"

[dependencies.matrix-sdk-crypto]
git = "https://github.com/matrix-org/matrix-rust-sdk"
rev = "fc3883d08e3ce9d04be39b1fc2867c21b973dbd7"
default_features = false
features = ["js", "backups_v1", "automatic-room-key-forwarding"]

[build-dependencies]
napi-build = "2.0.0"
