name: CI

permissions: {}

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Install Rust
        run: |
          rustup install nightly
          rustup default nightly
          rustup component add rustfmt

      - name: Check formatting
        run: |
          cargo fmt -- --check

      - name: Install Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version-file: .node-version

      - name: Install NPM dependencies
        run: npm install

      - name: run lint
        run: npm run lint

      - name: Check package version consistency
        run: |
          diff <(jq .version package.json) <(jq .version package-lock.json)
          diff <(jq .version package.json) <(jq '.packages[""].version' package-lock.json)

  test:
    name: test ${{ matrix.os-name }}, v${{ matrix.node-version }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true
      matrix:
        # Use Ubuntu LTS-1 for broader glibc compatibility.
        os: [ubuntu-22.04, macos-latest]
        node-version: [24.0, 25.0]
        include:
          - os: ubuntu-22.04
            os-name: 🐧

          - os: macos-latest
            os-name: 🍏

          - node-version: 24.0
            build-doc: true

    steps:
      - name: Checkout the repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Install Rust
        run: |
          rustup install stable
          rustup default stable

      - name: Load cache
        uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
        with:
          save-if: ${{ github.ref == 'refs/heads/main' }}

      - name: Install Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install NPM dependencies
        run: npm install

      - name: Build
        run: npm run release-build

      - name: Test
        run: npm run test

      # Building in dev-mode and copy lib in failure case
      - name: Build in non-release
        if: failure()
        run: |
          cp *.node release-mode-lib.node
          npm run build

      - uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        if: failure()
        with:
          name: Failure Files
          path: |
            bindings/matrix-sdk-crypto-nodejs/*.node
            /var/crash/*.crash

      - if: ${{ matrix.build-doc }}
        name: Build the documentation
        run: npm run doc

  docs:
    name: docs
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Install Protoc
        uses: arduino/setup-protoc@c65c819552d16ad3c9b72d9dfd5ba5237b9c906b # v3.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Rust
        run: |
          rustup install stable
          rustup default stable

      - name: Install Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version-file: .node-version

      - name: Load cache
        uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
        with:
          save-if: ${{ github.ref == 'refs/heads/main' }}

      - name: Build docs
        run: |
          npm install
          npm run build && npm run doc

      - name: Upload artifact
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@7b1f4a764d45c48632c6b24a0339c27f5614fb0b # v4.0.0
        with:
          path: './docs/'

      - name: Deploy to GitHub Pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5
